language: ruby
rvm:
- 2.2.2
deploy:
  provider: heroku
  api_key:
    secure: LmeqLbdIqWhDcZqRrGXhsTWnz24yGOQxlwmEr751uZ/V9sMv7tMQ7V6MCsvmRacip7vIjQ/B623j0zPjWIL8iM59veNrmw3xXwOWMSR/0gVInRjMfMeJKFZ5wFQJh3hdRkuGg1TcJ+5cAxnxBOkidIbJ40WDF4pYEWjLi1seiNg=
  app: agile-scrubland-5344
  on:
    repo: k158584/rakuten_enpit_example
    branch: master
